### ISSUE TITLE
OSError 32

### ISSUE THREAD

**Issue by mltbnz** [foxey/volumio-buddy#2]
Hi,
when running the volumio-buddy.py script I do get an error message:
`Traceback (most recent call last):
  File "/volumio/volumio-buddy/volumio_buddy/volumio_buddy.py", line 128, in _decode_rotary
    return self._callback_function(*self._callback_args)
  File "volumio-buddy.py", line 14, in update_volume
    pipe.write("volume_down")
  File "/volumio/volumio-buddy/volumio_buddy/volumio_buddy.py", line 595, in write
    os.write(self.pipeout, '%s\n' % command)
OSError: [Errno 32] Broken pipe`

Pretty new to RPI so maybe I connected the wrong pins? I changed `ROT_ENC_1A = 2 ROT_ENC_1B = 21` to the pins I connected using the BCM numbers but no success. Any idea?

**Comment by foxey** [comment]
The error is in the callback function triggered by the rotary encoder, so you did something right with the pins. The error indicates that the pipe between both processes is broken, probably because of an error in the part that handles the reads from the pipe (https://github.com/foxey/volumio-buddy/blob/master/volumio-buddy.py, lines 117-151). This can be the case when you don't have the OLED display connected, but still try to use it.
